general {
    lock_cmd = pidof hyprlock || hyprlock   # não abre segundo hyprlock se já estiver rodando
    before_sleep_cmd = loginctl lock-session # bloqueia antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on # liga tela ao acordar
}

listener {
    timeout = 300                           # 5 min: dimma o brilho
    on-timeout = brightnessctl -s set 10%   # salva estado atual e vai pra 10%
    on-resume = brightnessctl -r            # restaura brilho salvo
}

listener {
    timeout = 480                           # 8 min: bloqueia
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600                           # 10 min: desliga a tela
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
