general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 3          # segundos de graça antes de exigir senha
    no_fade_in = false
}

background {
    monitor =
    color = rgb(1a1b26)   # Tokyo Night bg sólido — troca por path de imagem depois
    blur_size = 4
    blur_passes = 2
    brightness = 0.7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(292e42)
    inner_color = rgb(24283b)
    font_color = rgb(c0caf5)
    fade_on_empty = true
    placeholder_text = <span foreground="##565f89">󰌾  Password...</span>
    hide_input = false
    check_color = rgb(9ece6a)
    fail_color = rgb(f7768e)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(e0af68)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(c0caf5)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B %Y')"
    color = rgb(565f89)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgb(7aa2f7)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}
